#!/bin/sh

# lint — Lint GitHub Actions

# Install MacPorts (https://github.com/melusina-org/gha-install-macports)
# This file is part of Install MacPorts.
#
# Copyright © 2022 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}

lint_sbcl()
{
    sbcl --noinform --disable-debugger "$@"
}

lint_main()
{
    lint_sbcl --load "${TOPLEVELDIR}/libexec/lisp/setup.lisp"\
	      --eval '(org.melusina.atelier:lint #p".")'
}

lint_main "$@"

# End of file `lint'
