#!/bin/sh

# configure_macports — Configure MacPorts

# Install MacPorts (https://github.com/melusina-org/gha-install-macports)
# This file is part of Install MacPorts.
#
# Copyright © 2022 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

prefix='/opt/local'

usage()
{
    cat <<'EOF'
Usage: configure_macports
 Configure MacPorts.
EOF
}

main()
{
    ensure_macos

    case "$#" in
	0)
	    :
	    ;;
	*)
	    1>&2 printf 'Failure: Too many arguments.\n'
	    usage
	    exit 64
	    ;;
    esac

    for file in variants sources; do
	source="${prefix}/etc/gha-install-macports/${file}.conf"
	destination="${prefix}/etc/macports/${file}.conf"
	if [ -f "${source}" ]; then
	    cp -f "{source}" "${destination}"
	fi
    done
}

main "$@"

# End of file `configure_macports'
