#!/bin/sh

# validate_prefix — Validate Prefix

# Install MacPorts (https://github.com/melusina-org/gha-install-macports)
# This file is part of Install MacPorts.
#
# Copyright © 2022 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

if ! [ "$1" = '/opt/local' ]; then
  1>&2 printf 'Failure: Only \047/opt/local\047 is a supported prefix\n'
  exit 1
fi

# End of file `validate_prefix'
