#!/bin/sh

# write_configuration — Write Configuration

# Install MacPorts (https://github.com/melusina-org/gha-install-macports)
# This file is part of Install MacPorts.
#
# Copyright © 2022 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

usage()
{
    cat <<'EOF'
Usage: write_configuration [-F|-S] PATHNAME CONTENTS
 Write configuration CONTENTS to PATHNAME.
Options:
 -S Handle CONTENTS as a string to write into PATHNAME.
 -P Handle CONTENTS as the pathname of a file to copy onto
    PATHNAME, unless this pathname does not designate any file.
EOF
}

main()
{
    local OPTARG OPTIND OPTION
    local filename contents dirname content_type

    content_type='string'
    while getopts 'SP' OPTION; do
	case "${OPTION}" in
	    S)
		content_type='string'
		;;
	    P)
		content_type='pathname'
		;;
	    *)
		1>&2 printf 'Failure: %s: Unsupported option..\n' "${OPTION}"
		usage
		exit 64
		;;
	esac
    done

    shift $((OPTIND - 1))

    case "$#" in
	2)
	    :
	    ;;
	*)
	    1>&2 printf 'Failure: Wrong number of arguments.\n'
	    usage
	    exit 64
	    ;;
    esac

    filename="$1"
    contents="$2"
    shift 2

    dirname=$(dirname "${filename}")

    if ! [ -d "${dirname}" ]; then
	install -d -o root -g wheel -m 700 "${dirname}"
    fi

    if [ "${content_type}" = 'string' ]; then
	install -o root -g wheel -m 644 /dev/null "${filename}"
	printf '%s' "${contents}" > "${filename}"
    elif [ "${content_type}" = 'pathname' -a -f "${contents}" ]; then
	install -o root -g wheel -m 644 /dev/null "${filename}"
	cp -f "${contents}" "${filename}"
    elif [ "${content_type}" = 'pathname' ]; then
	case "${contents}" in
	    .github/gha-install-macports/*.conf)
		:
		;;
	    *)
		1>&2 printf 'Failure: %s: File not found.\n' "${contents}"
		exit 1
	esac
    fi
}

main "$@"

# End of file `write_configuration'
